### ISSUE TITLE
Please offer an example in the step "Train and eval"

### ISSUE THREAD

**Issue by aiyolo** [bl0/negative-margin.few-shot#1]
I have no idea about how to set --config and --supp option, could you provide it directly?

**Comment by bl0** [comment]
Hi, the example scripts of the different datasets are provided in the `script` folder.
BTW, the `--config` parameter indicates the config files to use, which is in configs folder. and `--supp` option is used as a suffix of the output-dir. (Refer to https://github.com/bl0/negative-margin.few-shot/blob/master/lib/config.py#L105)

**Comment by aiyolo** [comment]
the default margin is 0.0 in the training stage, using this margin to train the model, I got a continuously increasing prec1, while if I change this margin to -0.3 as your paper says, prec1 will suddenly increase to 100, I don't understand this phenomenon.

**Comment by bl0** [comment]
The phenomenon is normal. If the model is trained with a large negative margin such as -0.3, then it will treat the uncorrected sample as corrected and the training top-1 precision will be almost 100% at the beginning.
But it still can learn transferable metrics that can be transferred to novel classes.

**Comment by bl0** [comment]
I am closing this issue due to a long time of inactivity, feel free to reopen it if there is any question. Thanks!
