### ISSUE TITLE
本篇论文中的3.4第一段

### ISSUE THREAD

**Issue by 9876K** [bl0/negative-margin.few-shot#15]
“the probability of a sample in the novel category j classified by pre-trained backbone fθ(m) and classifier W(m) as a base category k is..."这句话的意思是预测新类是某个基类的概率吗？就是说基类和新类有相同的类别吗，可是元学习中它们两个不应该有交叉啊，求指教

**Comment by bl0** [comment]
Hi, 感谢对我们工作的关注。
这段话的意思是，如果强行拿基类分类器来对新类数据进行分类，看同一个新类被分到同一个基类的概率，从而看基类和新类的相似度。
实际上基类和新类没有交叉哈，就像是拿一个猫狗分类器来对花草进行分类。
