### ISSUE TITLE
data distributions in angular space

### ISSUE THREAD

**Issue by ssxlconch** [bl0/negative-margin.few-shot#2]
Sorry for bothering,

May I ask how do you draw the FIG 3(the visualizations of the data distributions on angular space)?

Looking forward to your reply,

Best regards.

**Comment by bl0** [comment]
Hi, we firstly train a network with 2 dimension feature. Then we plot the histogram of feature angular using matplotlib.pyplot.hist with projection='polar'.
Reference: https://matplotlib.org/3.1.0/gallery/pie_and_polar_charts/polar_bar.html

**Comment by ssxlconch** [comment]
Oh I see!

You are so nice! Thank you for reply!
