### ISSUE TITLE
OSError: image file is truncated (39 bytes not processed)

### ISSUE THREAD

**Issue by DL-Alva** [bl0/negative-margin.few-shot#5]
Hi, when I test few shot accuracy for test set, it remind me "OSError: image file is truncated (39 bytes not processed)". I tried to use a smaller batchsize but it still didn't work. Would you know how to solve this problem?

**Comment by bl0** [comment]
It seems that your environment or data is incorrect.
I google the problem and find a solution: https://stackoverflow.com/questions/12984426/python-pil-ioerror-image-file-truncated-with-big-images.

**Comment by DL-Alva** [comment]
Thank you so much! The problem has been solved. I'm also confused that how to visualize the result on the images during the testing time?

**Comment by DL-Alva** [comment]
Thank you so much! The problem has been solved. I'm also confused that how to visualize the result on the images during the testing time.

**Comment by DL-Alva** [comment]
Thank you so much! The problem has been solved. I'm also confused that how to visualize the result on the images during the testing time.

**Comment by DL-Alva** [comment]
Thank you so much! The problem has been solved. I'm also confused that how to visualize the result on the images during the testing time.

**Comment by bl0** [comment]
What kind of visualization do you want?

**Comment by DL-Alva** [comment]
非常抱歉，我刚才的表述可能不太准确。我的意思是：代码中测试部分的输出结果只有一个总体的准确率，没有中间过程对每个测试样本的分类结果。如果我随机输入一张图片，用训练好的模型去预测图片类别，怎样才能输出预测结果呢？

发自我的iPhone


------------------ Original ------------------

**Comment by bl0** [comment]
可以在这里获取 score 之后，用 `pred = score.argmax(dim=1)` 获取预测结果。
https://github.com/bl0/negative-margin.few-shot/blob/3cd138ff6acbcdd4c94b5c989489d159e68a75e0/main.py#L181-L185

**Comment by DL-Alva** [comment]
好的，我尝试一下。非常感谢您☺️



发自我的iPhone


------------------ Original ------------------
