### ISSUE TITLE
how to train the model with res12？

### ISSUE THREAD

**Issue by ljjcoder** [bl0/negative-margin.few-shot#7]
when I train the model with your default config.py(resnet18, input size:224x224), it works well. However,  when I train neg-softmax_1-shot with resnet12(input size :84x84) as the backbone will cause an error of ‘out of memory’.  how many memory be requried for resnet12?

**Comment by bl0** [comment]
We will re-run the code to find out the memory usage of the different backbone for you.
Before that, you can reduce the batch size to ease the memory shortage problem.

**Comment by ljjcoder** [comment]
@bl0 thanks for your rely. Generally speaking, resnet12 needs less memory than resnet18. Moreover, the input size of resnet12 is only 84x84 and the input size of resnet18 is 224x224. Why do you use resnet12 so heavy?

**Comment by bl0** [comment]
The number of channel of ResNet12 is larger than resnet18.

https://github.com/bl0/negative-margin.few-shot/blob/3cd138ff6acbcdd4c94b5c989489d159e68a75e0/lib/backbone/resnet18.py#L146
https://github.com/bl0/negative-margin.few-shot/blob/3cd138ff6acbcdd4c94b5c989489d159e68a75e0/lib/backbone/resnet12.py#L80-L85

**Comment by impiga** [comment]
Hi, @ljjcoder . We re-run the code and find out ResNet-12 needs **~11,540 MB** while ResNet-18 needs **~9,000 MB**.

**Comment by ljjcoder** [comment]
@bl0 @impiga  To reduce the required memory， i  reduce the batch_size to 128 and run the code with resnet12. I get the result like bellow: 
![1601130333(1)](https://user-images.githubusercontent.com/40750189/94343080-3dd5d000-0048-11eb-9633-d70fd92d3837.png)
This result is very different from the result of your paper. Can you give me some useful suggestions to reproduce the result of your paper?

**Comment by bl0** [comment]
Hi, actually, for Resnet-18, `DropBlock` is not essential and we just set`drop_rate=0` for simplicity in the default config. 
But for Resnet-12, DropBlock is vital and you should set it to a positive value. 
For your convenience, We will add a new script that can reproduce the results with ResNet-12 in the paper. @impiga

**Comment by ljjcoder** [comment]
@bl0 do you finish the script of ResNet-12？

**Comment by impiga** [comment]
Hi, we added the scripts of ResNet-12 in the last commit. Please check them in the `script/resnet12` folder.
